services:
  wot-fdroid:
    image: caddy:2-alpine
    container_name: wot-fdroid
    hostname: 'wot-fdroid'
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./fdroid:/srv/fdroid:ro
    networks:
      - "net"

networks:
  net:
    external: true
